apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-volume-configmap
  labels:
    app: {{ include "chart.name" . }}
data:
{{ (tpl (.Files.Glob "config/config.json").AsConfig . ) | indent 2 }}

