kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-env-secret
type: Opaque
data:
{{- if .Values.database.password }}
  CLOUDANT_PASSWORD: {{ required "A valid .Values.database.password entry required!" .Values.database.password | b64enc | quote }}
{{- end }}
{{- if .Values.phiAccessLogDatabase.password }}
  CLOUDANT_PHI_LOG_PASSWORD: {{ required "A valid .Values.phiAccessLogDatabase.password entry required!" .Values.phiAccessLogDatabase.password | b64enc | quote }}
{{- end }}
{{- if .Values.redis.url }}
  REDIS_URL: {{ .Values.redis.url | b64enc | quote }}
{{- end }}
