{{- $profile := .Files.Glob "config/*profile*" }}
{{ if $profile }}
{{- $solutions := .Files.Glob "config/*solutions*" }}
{{ if $solutions }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-volume-secret
data:
{{ ($profile).AsSecrets | indent 2 }}
{{ ($solutions).AsSecrets | indent 2 }}
{{ end }}
{{ end }}